[build]
builder = "nixpacks"

[deploy]
startCommand = "node --import tsx src/server.ts"
healthcheckPath = "/api/genres"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
